### PR TITLE
Docker image based on Alpine

### PR DESCRIPTION
**Pull request by djaydev**
If you're interested in a Alpine version of the Docker image I believe this one should work.  It can be added as an additional tag like "lardbit/nefarious:alpine" if you prefer not to replace the primary image.

### CODE REVIEW

**Comment by lardbit** [comment]
What are the advantages of using alpine?  Does it reduce the file size of the image?  I'm all for it if so.

The ARM architecture (`Dockerfile-armv7`) is using ubuntu as well, but it looks like resin makes an arm+alpine as well:
https://www.balena.io/docs/reference/base-images/base-images/#supported-architectures-distros-and-languages

**Comment by djaydev** [comment]
Yes the image will shrink in total size.
For ARM images (or any docker image) I recommend official Docker base images.  For armv7 for example, I would recommend arm32v7/alpine:3.10

**Comment by lardbit** [comment]
Smaller is better.  I'll test this out.

I only chose Resin/Balena ARM images because their images can be built on x86 architecture and it uses **qemu** to emulate a different architectures (armv6, armv7 etc).  This way, **travis-ci** can do all the actual image building.  Do you know of an alternative?

**Comment by djaydev** [comment]
For qemu emulation you could add it to the Dockerfile, although that will increase the size of the image a few megabytes.

Example:
```
FROM arm32v7/alpine:3.10

COPY --from=balenalib/raspberrypi3-alpine /usr/bin/qemu-arm-static /usr/bin/qemu-arm-static
COPY --from=balenalib/raspberrypi3-alpine /usr/bin/resin-xbuild /usr/bin/resin-xbuild
COPY --from=balenalib/raspberrypi3-alpine /usr/bin/cross-build-start /usr/bin/cross-build-start
COPY --from=balenalib/raspberrypi3-alpine /usr/bin/cross-build-end /usr/bin/cross-build-end

RUN [ "cross-build-start" ]

EXPOSE 80

# add the main app
ADD src /app

# add the docker entrypoint
ADD docker-entrypoint.sh /app

WORKDIR /app

# install app dependencies, build app and remove dev dependencies
RUN apk --no-cache add \
    python3 \
    && apk --no-cache add --virtual=builddeps \
        build-base \
        npm \
        py3-virtualenv \
        python3-dev \
    && npm --prefix frontend install \
    && mkdir -p staticassets \
    && npm --prefix frontend run build-prod \
    && python3 -m venv /env \
    && /env/bin/pip install --no-cache-dir -r requirements.txt \
    && /env/bin/python manage.py collectstatic --no-input \
    && rm -rf frontend/node_modules \
    && apk del builddeps \
    && true

ENTRYPOINT ["/app/docker-entrypoint.sh"]

RUN [ "cross-build-end" ]
```

**Comment by lardbit** [comment]
Interesting.  I'll test that out.  Thanks.

**Pull request closed without merging**
