### PR TITLE
vpn support for arm

### PR DESCRIPTION
**Pull request by emorchy**
There are currently docker compose files with and without a vpn for an x86 architecture, but there is not a file with vpn support for arm. This docker compose file adds openvpn support for arm based devices.

### CODE REVIEW

**Comment by lardbit** [comment]
great - thanks for doing this.  I think I always knew raspberry pi owners wouldn't have a problem incorporating the vpn into the arm build.  I'm going to merge this and refactor is slightly to use the `docker-compose.base.yml` to keep the duplication down.

**Comment by lardbit** [comment]
@emorchy I updated nefarious to automatically work with multiple architectures (x86, arm etc) so there's no need for separate configurations anymore.   So, now you can just run the `docker-compose.transmission-vpn.yml` on your raspberry pi without any extra arm specific configuration.

**Comment by lardbit** [comment]
If you get a minute, I'd love to verify it's working on your end.  I just tested it on my raspberry pi 3 and it worked well.

**Comment by emorchy** [comment]
@lardbit Thank you for taking the time to edit your configuration to fit the needs of a raspberry pi. Unfortunately, my testing has shown that it is still incompatible with a Raspberry Pi 3B+. The first issue I found was the transmission container. Curl was not working for whatever reason, triggering a restart loop. This issue can be fixed by including a line in the docker container that allows privileged mode (`privileged: true`), but I heard about its insecurity. The second issue I faced involved both the nefarious and celery containers locked in restart loops. The log messages says `standard_init_linux.go:207: exec user process caused "exec format error"`. A quick search shows that this issue commonly appears when an image is built on a different architecture than it was intended. I hope this helps in fixing architecture compatibility, and I'm sorry I didn't bring good news.

**Comment by emorchy** [comment]
I can successfully build the Dockerfile on my x86 machine, but it fails on my Raspberry Pi 3B+.
Part of the `docker build .` output is below. I don't know what to make of this, but there were no x86 errors thrown:

added 1528 packages from 1242 contributors and audited 1535 packages in 562.539s

82 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

> nefarious@0.0.0 build-prod /app/frontend
> ng build --prod --output-path ../staticassets

Compiling @angular/animations : es2015 as esm2015
Compiling @angular/core : es2015 as esm2015
Warning: Worker #1 exited unexpectedly (code: null | signal: SIGKILL).
  Current task: {entryPoint: @angular/core, formatProperty: es2015, processDts: true}
  Current phase: compiling
Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Warning: Worker #2 exited unexpectedly (code: null | signal: SIGKILL).
  Current task: {entryPoint: @angular/platform-browser, formatProperty: es2015, processDts: true}
  Current phase: compiling
Compiling ngx-filesize : module as esm5
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! nefarious@0.0.0 build-prod: `ng build --prod --output-path ../staticassets`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the nefarious@0.0.0 build-prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-21T06_07_49_835Z-debug.log
The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends     build-essential     python3.8     python3.8-venv     python3.8-dev     python3.8-gdbm     virtualenv     gnupg     curl     git     authbind     && curl -sL https://deb.nodesource.com/setup_10.x | bash -     && apt-get install nodejs -y     && npm --prefix frontend install     && npm --prefix frontend run build-prod     && mkdir -p staticassets     && mkdir -p /nefarious-db     && python3.8 -m venv /env     && /env/bin/pip install --no-cache-dir -r requirements.txt     && /env/bin/python manage.py collectstatic --no-input     && rm -rf frontend/node_modules     && apt-get remove -y         build-essential         nodejs         python3.8-venv         python3.8-dev         virtualenv         curl         gnupg         git     && apt-get autoremove -y     && rm -rf /var/lib/apt/lists/*     && true' returned a non-zero code: 137

**Comment by lardbit** [comment]
I've seen the transmission curl issue you're talking about.  I've been following this issue on that [transmission/vpn](https://haugene.github.io/docker-transmission-openvpn/) project and have found that using the docker image tag **3.3** in your docker compose file seems to work well for me: 

    image:  haugene/transmission-openvpn:3.3

As for the arm build issue of nefarious, would you mind testing something else for me?  I also have a pi 3b and the new build is working ok.   To rule out the possibility of a stale/cached docker image, can you run the following and let me know what it says:
    
    docker run -it --entrypoint "/bin/cat" lardbit/nefarious:latest /app/.commit

It should return the git commit that the image is, which the newest is `1ebbdb4dfe476aa54d7f4a39c82c76b9d4429e84`.

Did you clone the repository again to make sure you have the most up-to-date version of the docker compose files? The main difference is the nefarious and celery images are now `lardbit/nefarious:latest` (vs lardbit/nefarous:armv7).

**Comment by lardbit** [comment]
oh, and regarding your logs trying to build the docker image, it was SIG killed, which probably means your pi ran out of memory and docker killed the process.  I've found the pi's aren't powerful enough to build the images.  I use travis-ci and now github actions to build the images for me.  It's kind of an intense operation.  Thankfully they do it for free :)

**Comment by emorchy** [comment]
Thank you for your diagnosis about the issues. I am happy to share that everything works exactly the way you thought. The nefarious image I have been using had the old tag ":armv7". Removing the image, cloning the repository, and changing the transmission image to ":3.3" worked like a charm. Everything is up and running on the Raspberry Pi 3B+. Thank you so much for your help throughout this past week and a half, and if there are any other issues or bugs that arise, I will definitely get in touch.

**Comment by lardbit** [comment]
Fantastic! Thank you for the help testing and troubleshooting with the raspberry pi

**Pull request closed without merging**
