### PR TITLE
feat: Support scoping jackett searches with filter

### PR DESCRIPTION
**Pull request by disaac**
[feat: Support scoping jackett searches with filter](https://github.com/lardbit/nefarious/commit/cc12db98e47d9291da0739010642c446594459a4)

* Created new setting for jackett that allows specifying a [filter-index](https://github.com/Jackett/Jackett?tab=readme-ov-file#filter-indexers) when not set will default to `all` leaving current behavior in place.
* Updated initial migrations to include new `nefarious_settings.jackett_filter_index`
* Updated `verify_settings_jackett` to include the set `nefarious_settings.jackett_filter_index` during verification
* Updated `get_jackett_search_url` to return with the current `nefarious_settings.jackett_filter_index` used.

Issue: [Fixes Issue https://github.com/lardbit/nefarious/issues/292](https://github.com/lardbit/nefarious/issues/292)

[chore: Lock in pip to version 24.0](https://github.com/lardbit/nefarious/commit/43a89804fc11a966fcbec25345a079d15999b8b7)

* Installing pip 24.0 to avoid build failure see [https://github.com/pypa/pip/issues/12063](https://github.com/pypa/pip/issues/12063)
* FIxes Issue https://github.com/lardbit/nefarious/issues/294

Issue: https://github.com/lardbit/nefarious/issues/294

[fix: Updating UI / Recreate migration](https://github.com/lardbit/nefarious/commit/01f5cf23539ffb7ece54a9f1b803a748f7ddeff5)

* Updated the UI to show the filter-index label
* Added link to documentation for filter-index for the label.
* Re ran migration to recreate after updates and deleted previous one.

Fixes: Issue https://github.com/lardbit/nefarious/issues/292

* Entered two new defects to track issues I worked around in this PR regarding updates to python pip and some packages. 

Related chore issues: Issue #294 and Issue #296

### CODE REVIEW

**Comment by disaac** [comment]
Fixes Issue #292 works around issue #294 until updated to support pip > 24.0. Should be Ready for merge as is.

**Comment by lardbit** [comment]
I'm excited to see all your contributions! I'm away all this week on
holiday so I'll get up to speed late next week. Thanks

**Comment by lardbit** [comment]
This looks good and works well for me.  I made some minor/cosmetic changes.

**Review by lardbit — DISMISSED** [review]
:+1:

**Pull request merged**
